### ISSUE TITLE
Fatal error occured on connection

### ISSUE THREAD

**Issue by nwmqpa** [CCM-Modding/CrayCrafting#4]
Hello , 
When I try to connect my client to a server , the server deconnect me with the message "A fatal error has occured , connection terminated"
This error come 10 seconds after my connection .
Can you help me or fix this error ?

**Comment by Claycorp** [comment]
You need to prove the error log that is on the server side. If you don't have access to that information there is really no way for us to help you.

**Comment by nwmqpa** [comment]
It is not on the server side , but I can give you the log from the two sides : 
Client : http://gyazo.com/bc3678193ce0e4959d47194e94eb66ed 
Server : http://gyazo.com/ac26b40ddee47fe6f2fd73e6283c0b04

**Comment by nwmqpa** [comment]
Can you resolve this problem ?

**Comment by dries007** [comment]
I'm looking into it

**Comment by Claycorp** [comment]
Can you post a mod list please?

**Comment by nwmqpa** [comment]
I think : http://pastebin.com/XAPphJVe
Sorry for the crach report , but I have 184 mods and do a list manually is a huge work

**Comment by dries007** [comment]
Oh damm, that chance of something going wrong there is huge. I'm going to put in some more debug information, so you can test with that version. (later tonight or tomorrow, don't have time atm)

**Comment by nwmqpa** [comment]
Yes , if you want
